### ISSUE TITLE
tslint compliant editor settings

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/knora-api-js-lib#12]
we should define settings for the editor so the config complies with the tslint settings

**Comment by tobiasschweizer** [comment]
see https://editorconfig.org

**Comment by tobiasschweizer** [comment]
sample config https://github.com/microsoft/TypeScript/blob/master/.editorconfig

**Comment by andreas-aeschlimann** [comment]
Unfortunately I do not know if PhpStorm/WebStorm really listens to these configs. For auto-format, I think you still need to configure the properties in the program. 

Maybe we can set up a settings repository for that?
https://www.jetbrains.com/help/phpstorm/sharing-your-ide-settings.html#settings-repository

**Comment by tobiasschweizer** [comment]
In Webstorm, the "EditorConfig" can be installed (or is installed by default). 

Unfortunately, the single/double quote setting is not supported yet by editorconfig (just a proposal: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#ideas-for-domain-specific-properties)

**Comment by tobiasschweizer** [comment]
see https://www.jetbrains.com/help/webstorm/configuring-code-style.html

once an `.editorconfig` file is created, its effects can be previewed. "Code- > Reformat Code" applies them.

**Comment by tobiasschweizer** [comment]
```
root = true

[{src,scripts}/**.{ts,json,js}]
end_of_line = crlf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4
```

**Comment by andreas-aeschlimann** [comment]
I see, but there are many settings in WebStorm, such as spacing in brackets, parameters, functions etc. I think we should share those settings somehow to prevent edit wars. If you want, I can try to investigate further.

**Comment by tobiasschweizer** [comment]
Let0s define some sensible defaults for DaSCH TypeScript code and see how much we can set in editorconfig (version controlled) and what needs to be set in the editor's settings

**Comment by musicEnfanthen** [comment]
You could have a look at [prettier](https://prettier.io/). Should be able to cover most of your needs.

**Comment by tobiasschweizer** [comment]
Thanks for the link. How did you deal with tslint? https://prettier.io/docs/en/integrating-with-linters.html
