### ISSUE TITLE
getNumberOfValues(prop) always >= 1, even if property has no values

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/knora-api-js-lib#53]
getNumberOfValues(prop) always returns a value >0 1, even if the property has no value.

**Comment by tobiasschweizer** [comment]
I cannot reproduce this. 

Could you please try the following:
- check out https://github.com/dhlab-basel/knora-api-js-lib-test/pull/4
- start the app (requires a running instance of Knora)
- click on button "Get anything testding"
- check the output in the template

<img width="248" alt="Screen Shot 2019-09-23 at 9 47 46 AM" src="https://user-images.githubusercontent.com/6000023/65409151-3ea9a580-dde7-11e9-8c3c-08ac4ea907f6.png">
 
I also tried with minified JS:
- check out https://github.com/dhlab-basel/knora-api-js-lib-test/pull/4
- run `npm run build`

I use nginx to serve this locally:

"/usr/local/etc/nginx/servers/knora-api-js-lib-test.conf":

```

     server {
     	    listen 8091;
    	    server_name knora-api-js-lib-test.local;
    	    root .../knora-api-js-lib-test/dist/knora-api-js-lib-test;

    	    location / {
            	     try_files $uri $uri/ /index.html;
    	    }

    	access_log /usr/local/etc/nginx/logs/knora-api-js-lib-test.local.access.log;
	}



```

**Comment by tobiasschweizer** [comment]
In addition, you can check out https://github.com/dhlab-basel/knora-api-js-lib-test/pull/4 and run the e2e tests: `nom run e2e`. 

There is still a problem with Chrome verison: https://github.com/dhlab-basel/knora-api-js-lib-test/issues/2#issuecomment-533031956

**Comment by lrosenth** [comment]
I resolved – not necessary
